# Generated by Django 5.1.1 on 2024-10-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_published_date_book_published_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='attribute',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.CharField(blank=True, choices=[('Novela', 'Novela'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Política', 'Política')], max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='target_audience',
            field=models.CharField(blank=True, choices=[('Adulto', 'Adulto'), ('Joven', 'Joven'), ('Niño', 'Niño')], max_length=50),
        ),
    ]
