# Generated by Django 5.1.1 on 2024-10-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_target_audience_book_target_audience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='target_audience',
        ),
        migrations.DeleteModel(
            name='TargetAudience',
        ),
        migrations.AddField(
            model_name='book',
            name='target_audience',
            field=models.CharField(blank=True, choices=[('Adulto', 'Adulto'), ('Joven', 'Joven'), ('Niño', 'Niño'), ('Universitario', 'Universitario')], max_length=50),
        ),
    ]
